### ISSUE TITLE
Auto detect device model and SDK version

### ISSUE THREAD

**Issue by xchapron-ledger** [LedgerHQ/speculos#316] opened 2022-08-11 12:48 UTC
We could probably embed additional information in the application generated elf file in order for Speculos to automatically retrieve the device model and SDK version.

In most cases, this would detect the proper SDK to use and allow to exit immediately with a proper message for the user when the SDK is not supported instead of :
- requesting the user to specify the proper SDK, which is not obvious, and an error result in syscall issues.
- defaulting to an SDK version that might not be the proper one, which would result in syscall issues.

**Comment by greenknot** [comment] 2022-08-11 12:51
Duplicate of issue #270.

**Comment by greenknot** [comment] 2022-08-11 12:56
(Thanks for the issue, though!)

**Closed by greenknot** 2022-08-11 12:56 UTC
Labels: enhancement
